### DISCUSSION TITLE
How to adjust parameters for Insta360 ONE X2?

### DISCUSSION THREAD

**Discussion by Shunmo17** [stella-cv/stella_vslam#158] [Q&A] [answered]
I use tracking and mapping of OpenVSLAM with RICOH Theta V and Insra360 ONE X2. Both cameras' config files were build based on the example file for RICOH Theta S 960 (https://github.com/OpenVSLAM-Community/openvslam/blob/main/example/aist/equirectangular.yaml), and I only changed video resolution and `max_num_keypoints`.

In order to evaluate the accuracy of OpenVSLAM, I ran it with the same video several times and compared these two cameras,  I noticed that the estimated trajectories in each trial of Insta360 ONE X2 vary wider than one of RICOH Theta V, and the difference from the ground truth was large when I used the video captured with Insta360 One X2. Therefore, I would like to adjust parameters for Insta360 ONE X2.

<p float="left">
  <img src="https://user-images.githubusercontent.com/45775392/132972707-2e785b49-807c-4110-8b79-42dcdfbba257.png" width="400" /> 
  <img src="https://user-images.githubusercontent.com/45775392/132972691-78325e13-a8a1-4736-a0b0-e4602a440180.png" width="400" />
Left: RICOH Theta V, Right: Insta360 ONE X2
</p>

I found the description of parameters (https://openvslam-community.readthedocs.io/en/latest/parameters.html), but I have no idea how to adjust these parameters especially ORB Parameters.

Could you tell me how to adjust parameters for the cameras not in example?

### Config file for RICOH Theta V
```
# Equirectangular model for RICOH THETA S

#==============#
# Camera Model #
#==============#

Camera:
  name: "RICOH THETA V"
  setup: "monocular"
  model: "equirectangular"

  fps: 30.0
  cols: 3840
  rows: 1920

  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

Tracking:
  max_num_keypoints: 5000

#================#
# ORB Parameters #
#================#

Feature:
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7
  mask_rectangles:
    - [0.0, 1.0, 0.0, 0.1]
    - [0.0, 1.0, 0.84, 1.0]
    - [0.0, 0.2, 0.7, 1.0]
    - [0.8, 1.0, 0.7, 1.0]

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
```

### Config file for Insta360 ONE X2
```

# Equirectangular model for RICOH THETA S

#==============#
# Camera Model #
#==============#

Camera:
  name: "Insta360 One X2"
  setup: "monocular"
  model: "equirectangular"

  fps: 30.0
  cols: 5760
  rows: 2880

  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

Tracking:
  max_num_keypoints: 5000

#================#
# ORB Parameters #
#================#

Feature:
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7
  mask_rectangles:
    - [0.0, 1.0, 0.0, 0.1]
    - [0.0, 1.0, 0.84, 1.0]
    - [0.0, 0.2, 0.7, 1.0]
    - [0.8, 1.0, 0.7, 1.0]

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
```
