### DISCUSSION TITLE
Can we use localization with a map generated by other camera?

### DISCUSSION THREAD

**Discussion by Shunmo17** [stella-cv/stella_vslam#168] [Q&A] [answered]
I would like to use localization with a smartphone and a map generated by mapping with RICOH Theta V, but it doesn't work at all when I tried.

Is OpenVSLAM can be used localization with map generated by the other camera? If yes, I would like to ask how to use it.

**Comment by ymd-stella** [comment, marked as answer]
See https://github.com/xdspacelab/openvslam/issues/388.

**Reply by Shunmo17** [reply]
In https://github.com/xdspacelab/openvslam/issues/388, you used RGB-D camera for mapping and THETA for localization.
Also, in https://github.com/OpenVSLAM-Community/openvslam/discussions/130, they discussed the combination of stereo camera and monocular camera, so I can't understand what should I do to use THETA for mapping and monocular for localization.

Could you give me some advice? My configuration is below,

### THETA V
```
  
# Equirectangular model for RICOH THETA S

#==============#
# Camera Model #
#==============#

Camera:
  name: "RICOH THETA V"
  setup: "monocular"
  model: "equirectangular"

  fps: 30.0
  cols: 3840
  rows: 1920

  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

Tracking:
  max_num_keypoints: 5000

#================#
# ORB Parameters #
#================#

Feature:
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7
  mask_rectangles:
    - [0.0, 1.0, 0.0, 0.1]
    - [0.0, 1.0, 0.84, 1.0]
    - [0.0, 0.2, 0.7, 1.0]
    - [0.8, 1.0, 0.7, 1.0]

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
```

### Monocular camera
```

# EuRoC monocular model

#==============#
# Camera Model #
#==============#

Camera:
  name: "EuRoC monocular"
  setup: "monocular"
  model: "perspective"

  fx: 3301.75634177063
  fy: 3301.75667878999
  cx: 1519.47077570314
  cy: 2038.17999864472

  k1: 0.258213744666496
  k2: -1.72524450365418
  p1: 0.000864017173186503
  p2: -0.000184655041068498
  k3: 3.36297074477602

  fps: 30.0
  cols: 4032
  rows: 3024

  # Gray, RGB, RGBA, BGR, BGRA
  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

Tracking:
  max_num_keypoints: 2000
  ini_max_num_keypoints: 4000

#================#
# ORB Parameters #
#================#

Feature:
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 0.07
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.08
  camera_line_width: 3
  viewpoint_x: 0
  viewpoint_y: -0.65
  viewpoint_z: -1.9
  viewpoint_f: 400
```
