### DISCUSSION TITLE
slam and localization with smartphone

### DISCUSSION THREAD

**Discussion by LaurentClaessens** [stella-cv/stella_vslam#320] [Q&A] [answered]
I try to make the whole work using videos/images of a simple smartphone.

- Everything works well (slam+relocalization) in the docker with the given examples.

- I calibrated my camera using [openCV](https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html)
- Since OpenCV provides the parameters (k1, k2, p1, p2, k3), I choose model = "perspective"

Here is the configuration file I wrote:

```
# MY CAMERA

#==============#
# Camera Model #
#==============#

Camera:
  name: "my phone"
  setup: "monocular"
  model: "perspective"      # perspective because (k1,k2,p1,p2,k3)

  fx: 717.5441865449359
  fy: 717.3357307728804
  cx: 275.1399472883436
  cy: 494.3278242124892

  k1: 0.188964976862215
  k2: -0.7832848453245175
  p1: 0.0056395837369071595
  p2: 0.00024236895916318884
  k3: 0.8077997128156118


  # from the metadata of the video I shot
  fps: 20
  cols: 1920        
  rows: 1080        

  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

Preprocessing:
  min_size: 800

#================#
# orb parameters #
#================#

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#========================#
# Initializer Parameters #
#========================#

Initializer:
  scaling_factor: 5.0

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
```

Using this configuration file and the video I shot with my camera does not work: I see the video in the server (localhost:3001) but the small green rectangle does not follow the movement.

What I am doing wrong ? Is there a phase of preparation of the video ? Some setting I missed ?
