### DISCUSSION TITLE
camera calibration parameters

### DISCUSSION THREAD

**Discussion by zoldaten** [stella-cv/stella_vslam#527] [Q&A] [answered]
hi.
i`m trying to implement camera calibration parameters got after Kalibr camera calibration:
```
 cam0:
  camera_model: pinhole
  distortion_coeffs: [0.11229715732461544, -0.15069645913928714, 0.0014552750357630418, 0.0008802552075759202]
  distortion_model: radtan
  intrinsics: [351.7740605661654, 468.9451131575785, 290.71349241118145, 235.78276791924256]
  line_delay: 6.508060238881519e-05
  resolution: [640, 480]
  rostopic: /image_raw
```

I saw it should be looking like this -
`https://github.com/stella-cv/stella_vslam/blob/f42bfcfabbaf3e4fd0021ac3e283bb89a4312db9/example/tum_rgbd/TUM_RGBD_mono_1.yaml`

but what goes where ?
![Screenshot_2](https://github.com/stella-cv/stella_vslam/assets/29411817/67497df9-02ad-4b96-886c-618fffd36406)

how to calculate k3 if distortion_coeffs have only 4 members ?
