### DISCUSSION TITLE
OpemVSLAM using socket viewer: error while loading ORB vocabulary for UVC camera

### DISCUSSION THREAD

**Discussion by Udaykiran87** [stella-cv/stella_vslam#94] [Q&A] [answered]
Hello Community,

Thank you so much for continuous support from community for my questions in other threads.

I am having another issue.
**Question 1:**
I am using 'logicool C270n' webcam for OpenVSLAM. Number of camera used is 1.
I downloaded vocabulary as mentioned below:
https://openvslam-community.readthedocs.io/en/latest/example.html#slam-with-uvc-camera

After calibration (using OpenCV chessboard method) i updated camera.yaml as below.

```
# UVC monocular model

#==============#
# Camera Model #
#==============#

Camera:
  name: "logicool"
  setup: "monocular"
  model: "perspective"

  fx: 820.68303564
  fy: 820.51434565
  cx: 310.87149613
  cy: 231.63407464

  k1: 0.037160015
  k2: 1.96485337
  p1: 0.00136894818
  p2: 0.0084237012
  k3: -16.9908964

  fps: 30.0
  cols: 640
  rows: 480

  color_order: "RGB"
```

But when i run OpenVSLAM i get below error (written in bold) under **Error log**:
I am not sure is it because **ORB parameters** are missing in my yaml file? If yes i do not know how to get or calculate it? What else is missing in my yaml file? I could not find any **.yaml example** for reference in github repo or anywhere in internet.
Could you please guide me to solve the issue.

Command executed:
 **./run_camera_slam -v ./orb_vocab.fbow -n 0 -c ../example/aist/camera.yaml --map-db camera_home1.msg**

Note:
I tried with n = 0 and n = 1. I am not sure what is the correct value. Could you please suggest for single camera.

**Error log:**
[2021-05-14 10:16:47.995] [I] config file loaded: ../example/aist/camera.yaml
[2021-05-14 10:16:47.996] [I] 
  ___               __   _____ _      _   __  __ 
 / _ \ _ __  ___ _ _\ \ / / __| |    /_\ |  \/  |
| (_) | '_ \/ -_) ' \\ V /\__ \ |__ / _ \| |\/| |
 \___/| .__/\___|_||_|\_/ |___/____/_/ \_\_|  |_|
      |_|                                        

Copyright (C) 2019,
National Institute of Advanced Industrial Science and Technology (AIST)
All rights reserved.

This is free software,
and you are welcome to redistribute it under certain conditions.
See the LICENSE file.

Camera:
  k1: 0.037160015
  cy: 231.63407464
  k2: 1.96485337
  setup: !<!> monocular
  cx: 310.87149613
  name: !<!> logicool
  fx: 820.68303564
  fy: 820.51434565
  model: !<!> perspective
  p1: 0.00136894818
  p2: 0.0084237012
  k3: -16.9908964
  fps: 30.0
  cols: 640
  rows: 480
  color_order: !<!> RGB

[2021-05-14 10:16:47.996] [I] loading ORB vocabulary: ./orb_vocab.fbow
**[2021-05-14 10:16:48.016] [E] failed in loading ORB parameters: yaml-cpp: error at line 0, column 0: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
terminate called after throwing an instance of 'YAML::InvalidNode'
  what():  yaml-cpp: error at line 0, column 0: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
*** Aborted at 1620987408 (unix time) try "date -d @1620987408" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x15) received by PID 21 (TID 0x7f952c4010) from PID 21; stack trace: ***
    @       0x7f9c4ff6c0 ([vdso]+0x6bf)
    @       0x7f9b4dd4f8 raise
Aborted (core dumped)**

**Question 2:**
Can i assume that there is no distortion in camera and no need to calibrate my webcam. This is the condition given to me in my project. In such case is there a way that we can run  OpenVSLAM without giving .yaml as input?

I would appreciate any kind of help or guidance.

Thanks and Regards,
Udaykiran Patnaik.
